#:schema node_modules/wrangler/config-schema.json
name = "anbu-weddings"
pages_build_output_dir = "build"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# Add non-sensitive variables here
NODE_VERSION = "20"

# [[kv_namespaces]]
# If you need KV storage
# binding = "MY_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxx"
